### PR TITLE
This is a question

### PR DESCRIPTION
**Pull request by deskafeina**
I'm not sure how to contact you, so I created this pull request.

Please, would you mind explain me what's the difference between your plugin and the official one?

The later used to work, but now it shows some error about dazn not supported in my region, but that's not correct. However, with your plugin version it works perfectly. Good job!

### CODE REVIEW

**Comment by Maven85** [comment]
My addon is based on the official addon from kodi, but with improvements and fixes since development has stopped.

You can see my changes in the commit history.

**Comment by deskafeina** [comment]
Thanks for your response.

Then, is this repo a fork of another repo? This is the initial commit (https://github.com/Maven85/plugin.video.dazn/commit/f3a56f1a20240d5b6b2253fa9c3e69ab587a5553) but I don't know exactly which repo did you copy as de initial one.

By the way, the plugin right now doesn't reproduce any channel, this is why I'm trying to understand how it works to provide a solution.

**Comment by Maven85** [comment]
Yes, this addon is a fork of the original, but the original author has since deleted his repository.

Which channels do you mean?

**Comment by deskafeina** [comment]
I'm sorry, Dazn channels (or sources, videos, call it as you wish) are working now. Tested in Kodi for Windows. Maybe it was a temporary problem.

Thanks for your work, really appreciate it !!

**Pull request closed without merging**
